### ISSUE TITLE
How do you post a sound file.mp3 or URL?

### ISSUE THREAD

**Issue by herrtodd33** [herrtodd33/southwestdata#4]
@d4rkd0s 
not sure how to post sound file.mp3 or URL ?
I didn't think it would be handled the same as a picture-
echo "<img style='width:30px; height:30px; border-radius:3px;' src='" . $animal['photo'] . "'><br><i>" . $animal['photo'] . "</i>";
            echo "</td>";
            echo "</tr>";
I have this so far for the sound but its not posting in the correct cell/row&column
echo $animal["lifespan"];
            echo "</td>";
            echo "<td>";

**Comment by d4rkd0s** [comment]
@herrtodd33  What do you mean by "post"?

Do you mean POST like the HTTP verb (https://en.wikipedia.org/wiki/POST_(HTTP)) Where you are pushing a mp3 over the internet to the server? (ex: to save a new sound file to the database)

Or do you mean display like rendering the sound file on the page, via the "path to the file" that's saved in the database?

Or do you mean "post" as in something else?

**Comment by herrtodd33** [comment]
On Thu, Aug 24, 2017 at 1:02 PM Logan Schmidt <notifications@github.com>
wrote:

> @herrtodd33 <https://github.com/herrtodd33> What do you mean by "post"?
>
> Do you mean POST like the HTTP verb (
> https://en.wikipedia.org/wiki/POST_(HTTP)) Where you are pushing a mp3
> over the internet to the server? (ex: to save a new sound file to the
> database)
>
> Or do you mean display like rendering the sound file on the page, via the
> "path to the file" that's saved in the database?
>
> Or do you mean "post" as in something else?
>
How to display MP3 on southwestdata/admin.php page.

**Comment by d4rkd0s** [comment]
@herrtodd33 You would do what you did here.

https://github.com/herrtodd33/southwestdata/blob/712ef12d75993034bbd3a61795d232898d188a82/renderBird.php#L36-L39

**Comment by d4rkd0s** [comment]
Where `$bird['sound']` is a string, a path to the sound file

**Comment by herrtodd33** [comment]
Thank you . I will give that a try today.
