### ISSUE TITLE
When you click on Add Animal or Bird button - you get error

### ISSUE THREAD

**Issue by herrtodd33** [herrtodd33/southwestdata#6]
When you click on Add Animal or Bird button, on the http://southwestdata.info/admin/admin_system.php page - you get error:
404 Not Found
nginx/1.10.3 (Ubuntu)

Github @d4rkd0s

**Comment by d4rkd0s** [comment]
Looks like you had a find and replace error...

![image](https://user-images.githubusercontent.com/2348814/29906894-0e0ff648-8dcd-11e7-8363-79165c16155b.png)

**Comment by d4rkd0s** [comment]
the action should be a real file, I doubt you have a file called `add_.php`

**Comment by herrtodd33** [comment]
Thank you, I will repair.
Fixed.
Github @d4rkd0s
